ZarzadzanieProjektem/Controllers/DokumentacjaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ZarzadzanieProjektem.DAL;
using ZarzadzanieProjektem.Models;

namespace ZarzadzanieProjektem.Controllers
{
    public class DokumentacjaController : Controller
    {
        private ProjectContext db = new ProjectContext();
        // GET: Dokumentacja
        [Authorize(Roles = "Administrator,Student")]
        public ActionResult Index()
        {
            return View();
        }
        [Authorize(Roles = "Administrator,Student")]
        public ActionResult Download(int? Id)
        {
            Dokumentacja doc = db.Dokumentacjas.First(e => e.DokumentacjaId == Id);
            db.Entry(doc).Reference("Plik").Load();
            FileContentResult res= new FileContentResult(doc.Plik.Plik, MimeMapping.GetMimeMapping(doc.NazwaPliku));
            res.FileDownloadName = doc.NazwaPliku;
            return res;
        }
    }
}

ZarzadzanieProjektem/Controllers/OsobasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ZarzadzanieProjektem.DAL;
using ZarzadzanieProjektem.Models;

namespace ZarzadzanieProjektem.Controllers
{
    public class OsobasController : Controller
    {
        private ProjectContext db = new ProjectContext();

        // GET: Osobas
        [Authorize(Roles = "Administrator")]
        public ActionResult Index()
        {
            return View(db.osobaEntities.ToList());
        }

        // GET: Osobas/Details/5
        [Authorize(Roles = "Administrator")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Osoba osoba = db.osobaEntities.Find(id);
            if (osoba == null)
            {
                return HttpNotFound();
            }
            return View(osoba);
        }

        // GET: Osobas/Create
        [Authorize(Roles = "Administrator")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Osobas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public ActionResult Create([Bind(Include = "OsobaId,Imie,Nazwisko")] Osoba osoba)
        {
            if (ModelState.IsValid)
            {
                db.osobaEntities.Add(osoba);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(osoba);
        }

        // GET: Osobas/Edit/5
        [Authorize(Roles = "Administrator")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Osoba osoba = db.osobaEntities.Find(id);
            if (osoba == null)
            {
                return HttpNotFound();
            }
            return View(osoba);
        }

        // POST: Osobas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public ActionResult Edit([Bind(Include = "OsobaId,Imie,Nazwisko")] Osoba osoba)
        {
            if (ModelState.IsValid)
            {
                db.Entry(osoba).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(osoba);
        }

        // GET: Osobas/Delete/5
        [Authorize(Roles = "Administrator")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Osoba osoba = db.osobaEntities.Find(id);
            if (osoba == null)
            {
                return HttpNotFound();
            }
            return View(osoba);
        }

        // POST: Osobas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public ActionResult DeleteConfirmed(int id)
        {
            Osoba osoba = db.osobaEntities.Find(id);
            db.osobaEntities.Remove(osoba);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ZarzadzanieProjektem/Views/Osobas/Create.cshtml
@model ZarzadzanieProjektem.Models.Osoba

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Osoba</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Imie, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Imie, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Imie, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nazwisko, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nazwisko, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nazwisko, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ZarzadzanieProjektem/Views/Osobas/Delete.cshtml
@model ZarzadzanieProjektem.Models.Osoba

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Osoba</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Imie)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Imie)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nazwisko)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nazwisko)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ZarzadzanieProjektem/Views/Osobas/Details.cshtml
@model ZarzadzanieProjektem.Models.Osoba

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Osoba</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Imie)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Imie)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nazwisko)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nazwisko)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.OsobaId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ZarzadzanieProjektem/Views/Osobas/Edit.cshtml
@model ZarzadzanieProjektem.Models.Osoba

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Osoba</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.OsobaId)

        <div class="form-group">
            @Html.LabelFor(model => model.Imie, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Imie, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Imie, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nazwisko, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nazwisko, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nazwisko, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ZarzadzanieProjektem/Views/Osobas/Index.cshtml
@model IEnumerable<ZarzadzanieProjektem.Models.Osoba>

@{
    ViewBag.Title = "Index";
}
@section Scripts {
    @Scripts.Render("~/bundles/projectViewScripts")
}
<h2>Index</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Imie)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nazwisko)
        </th>
        <th>
            Projekt(y)
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Imie)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Nazwisko)
        </td>
        <td>
            <table class="table">
                <tr>
                    <th>Tytuł projektu</th>
                    <th>Akcja</th>
                    <th>GitHub</th>
                    <th>Realizacja</th>
                    <th>Założenia</th>
                </tr>
                @if (item.ProjektClaimed != null)
                {
                <tr class="success">
                    <td>@Html.DisplayFor(it=>item.ProjektClaimed.Projekt.Tytul)</td>
                    <td>
                        @if (!String.IsNullOrEmpty(item.ProjektClaimed.GitHubLink) || item.ProjektClaimed.Dokumentacja != null)
                        {
                        <button class="btn customButtonSize btn-info btn-xs">
                            Realizowany
                        </button>
                        }
                        else
                        {
                            <button class="btn customButtonSize btn-info btn-xs">
                                Oczekuje
                            </button>
                        }
                    </td>
                    <td>
                    @if (!String.IsNullOrEmpty(item.ProjektClaimed.GitHubLink))
                    {
                        <button target="_blank" onclick="window.open('@item.ProjektClaimed.GitHubLink','_blank')" class="customButtonSize btn btn-xs btn-info">Link</button>
                    }
                    else
                    {
                        <button class="customButtonSize btn btn-danger btn-xs">Brak</button>
                    }
                    </td>
                    <td>
                    @if (item.ProjektClaimed.Dokumentacja != null)
                    {
                        <button onclick="location.href='@Url.Action("Download", "Dokumentacja", new { Id = item.ProjektClaimed.Dokumentacja.DokumentacjaId })';return false;" class="customButtonSize btn btn-xs btn-primary">Pobierz</button>
                    }
                    else
                    {
                        <button class="btn customButtonSize btn-danger btn-xs">Brak</button>
                    }
                    </td>
                    <td>
                        @if (item.ProjektClaimed.DokumentacjaZalozen != null)
                    {
                            <button onclick="location.href='@Url.Action("Download", "Dokumentacja", new { Id = item.ProjektClaimed.DokumentacjaZalozen.DokumentacjaId })';return false;" class="customButtonSize btn btn-xs btn-primary">Pobierz</button>
                        }
                        else
                        {
                            <button class="btn customButtonSize btn-danger btn-xs">Brak</button>
                        }
                    </td>              
                </tr>
                }
                else
                {
                    <tr class="success">
                        <td colspan="5"><center>Brak zaakceptowanych projektów</center></td>
                    </tr>
                }
                @if (item.NonClaimedProjekts.Any())
                {
                    foreach (var claim in item.NonClaimedProjekts)
                    {

                        if (item.ProjektClaimed == null || item.ProjektClaimed.Projekt != claim)
                        {
                            <tr class="warning">
                                <td>@Html.DisplayFor(it => claim.Tytul)</td>
                                <td>
                                    @if (item.ProjektClaimed == null)
                                    {
                                        <button onclick="claimFinal(@item.OsobaId,@claim.ProjectId)" id="@String.Format("btnClaimFinal{0}", claim.ProjectId)" class="customButtonSize claimFinalButton btn btn-success btn-xs" type="submit">
                                            Zaakceptuj
                                        </button>
                                    }
                                    else
                                    {
                                        if (String.IsNullOrEmpty(item.ProjektClaimed.GitHubLink)||item.ProjektClaimed.Dokumentacja==null)
                                        {
                                            <button onclick="claimFinal(@item.OsobaId,@claim.ProjectId)" id="@String.Format("btnClaimFinal{0}", claim.ProjectId)" class="customButtonSize claimFinalButton btn btn-warning btn-xs" type="submit">
                                                Zmień
                                            </button>
                                        }
                                        else
                                        {
                                            <button class="btn customButtonSize btn-info btn-xs">
                                                Realizowany
                                            </button>
                                        }
                                    }
                                </td>
                                <td><button class="btn customButtonSize btn-danger btn-xs">Brak</button></td>
                                <td><button class="btn customButtonSize btn-danger btn-xs">Brak</button></td>
                                <td><button class="btn customButtonSize btn-danger btn-xs">Brak</button></td>
                            </tr>
                        }
                    }
                }
            </table>
            @*@Html.ActionLink("Edit", "Edit", new { id=item.OsobaId }) |
            @Html.ActionLink("Details", "Details", new { id=item.OsobaId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.OsobaId })*@
        </td>
    </tr>
}
</table>