ZarzadzanieProjektem/Controllers/SingleProjectController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ZarzadzanieProjektem.DAL;
using ZarzadzanieProjektem.Models;

namespace ZarzadzanieProjektem.Controllers
{
    public class SingleProjectController : Controller
    {
        private ProjectContext db = new ProjectContext();
        private ApplicationUser user;
        private Osoba osoba;
        // GET: SingleProject
        [Authorize(Roles = "Administrator,Student")]
        public ActionResult Index()
        {
            user= System.Web.HttpContext.Current.GetOwinContext().GetUserManager<ApplicationUserManager>().FindById(System.Web.HttpContext.Current.User.Identity.GetUserId());
            osoba= db.osobaEntities.First(e => e.OsobaId == user.Details.OsobaId);
            if (osoba.ProjektClaimed == null)
            {
                return View("WithoutFinalClaim", osoba.NonClaimedProjekts);
            }
            return View(osoba.ProjektClaimed);
        }
        //public ActionResult Add()
        //{
        //    return new HttpStatusCodeResult(500);
        //}
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator,Student")]
        public ActionResult Add([Bind(Include = "ProjectDetailsId,GitHubLink")] ProjectDetails projectDetails, [Bind(Include = "DokumentacjaId,NazwaPliku,Rozszerzenie,Plik")] Dokumentacja dokumentacja, HttpPostedFileBase upload,HttpPostedFileBase upload2)
        //public ActionResult Add(HttpPostedFileBase upload)
        {
            if (ModelState.IsValid)
            {
                if (upload != null && upload.ContentLength > 0)
                {
                    db.Database.Log = s => System.Diagnostics.Debug.WriteLine(s);
                    ProjectDetails det=db.ProjectDetails.First(e => e.ProjectDetailsId == projectDetails.ProjectDetailsId);
                    det.GitHubLink = projectDetails.GitHubLink;
                    MemoryStream target = new MemoryStream();
                    upload.InputStream.CopyTo(target);
                    byte[] data = target.ToArray();
                    BinaryData FileData = new BinaryData { Plik = data };
                    dokumentacja.Plik = FileData;
                    dokumentacja.NazwaPliku = upload.FileName;
                    dokumentacja.Rozszerzenie = Path.GetExtension(upload.FileName).Replace(".", "");
                    MemoryStream target2 = new MemoryStream();
                    upload2.InputStream.CopyTo(target2);
                    byte[] data2 = target2.ToArray();
                    BinaryData FileData2 = new BinaryData { Plik = data2 };
                    Dokumentacja Zalozenia = new Dokumentacja();
                    Zalozenia.Plik = FileData2;
                    Zalozenia.NazwaPliku = upload2.FileName;
                    Zalozenia.Rozszerzenie = Path.GetExtension(upload2.FileName).Replace(".", "");
                    db.Entry(dokumentacja).State = System.Data.Entity.EntityState.Added;
                    db.Entry(Zalozenia).State = System.Data.Entity.EntityState.Added;
                    db.SaveChanges();
                    det.Dokumentacja = dokumentacja;
                    det.DokumentacjaZalozen = Zalozenia;
                    db.Entry(det).State = System.Data.Entity.EntityState.Modified;
                    db.SaveChanges();
                }
            }
            ApplicationUser user;
            Osoba osoba;
            user = System.Web.HttpContext.Current.GetOwinContext().GetUserManager<ApplicationUserManager>().FindById(System.Web.HttpContext.Current.User.Identity.GetUserId());
            osoba = db.osobaEntities.First(e => e.OsobaId == user.Details.OsobaId);
            return View(osoba.ProjektClaimed);
        }


    }
}

ZarzadzanieProjektem/Views/SingleProject/Add.cshtml
@model ZarzadzanieProjektem.Models.ProjectDetails

@{
    ViewBag.Title = "Index";
}

<div class="row">
    <div class="col-md-5">
        <h4>O projekcie</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Projekt.Tytul)
            </dt>

            <dd>
                @Html.TextAreaFor(model => model.Projekt.Tytul, 1, 50, new { @class = "form-control" })
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Projekt.Opis)
            </dt>

            <dd>
                @Html.TextAreaFor(model => model.Projekt.Opis, 5, 50, new { @class = "form-control" })
                
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Projekt.Wymagania)
            </dt>

            <dd>
                @Html.TextAreaFor(model => model.Projekt.Wymagania, 5, 50, new { @class = "form-control" })
            </dd>
            </dl>

</div>
    <div class="col-md-7">
        @using (Html.BeginForm("Add", "SingleProject", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h4>Dodaj/Zmień Dokumenty</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.ProjectDetailsId)
                @Html.HiddenFor(model => model.Projekt)

                <div class="form-group">
                    @Html.LabelFor(model => model.GitHubLink, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.GitHubLink, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.GitHubLink, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.Label("Dokumentacja założen", new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <input type="file" id="Dokumentacja" name="upload2" />
                    </div>
                </div>
                <div class="form-group">
                    @Html.Label("Dokumentacja z realizacji", new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <input type="file" id="Dokumentacja" name="upload" />
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Save" class="btn btn-default" />
                    </div>
                </div>
                <h4>Szczegóły projektu zaktualizowane</h4>
            </div>
        }
    </div>
</div>
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ZarzadzanieProjektem/Views/SingleProject/Index.cshtml
@model ZarzadzanieProjektem.Models.ProjectDetails

@{
    ViewBag.Title = "Index";
}

<div class="row">
    <div class="col-md-5">
        <h4>O projekcie</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Projekt.Tytul)
            </dt>

            <dd>
                @Html.TextAreaFor(model => model.Projekt.Tytul, 1, 50, new { @class = "form-control" })
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Projekt.Opis)
            </dt>

            <dd>
                @Html.TextAreaFor(model => model.Projekt.Opis, 5, 50, new { @class = "form-control" })
                
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Projekt.Wymagania)
            </dt>

            <dd>
                @Html.TextAreaFor(model => model.Projekt.Wymagania, 5, 50, new { @class = "form-control" })
            </dd>
            </dl>

</div>
    <div class="col-md-7">
        @using (Html.BeginForm("Add", "SingleProject", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h4>Dodaj/Zmień Dokumenty</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.ProjectDetailsId)
                @Html.HiddenFor(model => model.Projekt)

                <div class="form-group">
                    @Html.LabelFor(model => model.GitHubLink, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.GitHubLink, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.GitHubLink, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.Label("Dokumentacja założen", new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <input type="file" id="Dokumentacja" name="upload2" />
                    </div>
                </div>
                <div class="form-group">
                    @Html.Label("Dokumentacja z realizacji", new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <input type="file" id="Dokumentacja" name="upload" />
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Save" class="btn btn-default" />
                    </div>
                </div>
            </div>
        }
    </div>
</div>
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ZarzadzanieProjektem/Views/SingleProject/WithoutFinalClaim.cshtml
@model List<ZarzadzanieProjektem.Models.Project>
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<h1>Nie zostałeś jeszcze zakwalifikowany do żadnego projektu, poczekaj aż prowadzący zaakceptuje twoje uczestnictwo w projekcie.</h1>
<p>Wyraziłeś chęć do uczestniczenia w projektach:</p>
@foreach (var item in Model)
{
    <p>@Html.DisplayFor(modelItem => item.Tytul)</p>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}